#!/bin/bash

if [[ ! -f "${HOME}/.saferc" ]]; then
	echo "No .saferc found. Please connect to a working Sawmill installation."
	exit 1
fi

safe targets
read -p "Use this Sawmill for storing deployment credentials?  [yes or no] " -r YESNO
if [[ "${YESNO}" != "yes" && "${YESNO}" != "y" ]]; then
  echo "ABORTING..."
  exit 1
fi
